from setuptools import setup, find_namespace_packages

scm_version_template = """# Generated by setuptools_scm
__all__ = ["__version__"]

__version__ = "{version}"
"""

setup(
    name="ts_bokeh_apps",
    description="Bokeh visualization apps.",
    use_scm_version={
        "write_to": "python/lsst_ts/bokeh/apps/version.py",
        "write_to_template": scm_version_template,
    },
    setup_requires=["setuptools_scm"],
    package_dir={"": "python"},
    packages=find_namespace_packages(where="python"),
    package_data={"": ["*.rst", "*.yaml", "*.html", "*.css", "*.js", "*.svg"]},
    scripts=[],
    license="GPL",
    project_urls={
        "Bug Tracker": "https://jira.lsstcorp.org/secure/Dashboard.jspa",
        "Source Code": "https://github.com/lsst-ts/ts_bokeh_apps",
    },
)
